#ifndef MLIR_DIALECT_STENCIL_STENCILOPS_H
#define MLIR_DIALECT_STENCIL_STENCILOPS_H

#include "mlir/IR/Function.h"
#include "Dialect/Stencil/StencilTypes.h"

namespace mlir {
namespace stencil {

/// Retrieve the class declarations generated by TableGen
#define GET_OP_CLASSES
#include "Dialect/Stencil/StencilOps.h.inc"

} // namespace stencil
} // namespace mlir

#endif // MLIR_DIALECT_STENCIL_STENCILOPS_H
